# Generated by Django 3.0.7 on 2020-06-30 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atencion',
            fields=[
                ('id_atencion', models.AutoField(primary_key=True, serialize=False)),
                ('rut_medico', models.CharField(max_length=12, unique=True)),
                ('nombre_medico', models.CharField(max_length=40)),
                ('rut_paciente', models.CharField(max_length=12)),
                ('nombre_paciente', models.CharField(max_length=40)),
                ('fecha_atencion', models.DateField()),
                ('consulta', models.CharField(max_length=200)),
                ('procedimiento', models.CharField(max_length=200)),
                ('receta', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'atenciones',
            },
        ),
    ]
